version: '2.1'

networks:
  crawler-net:
     driver: bridge

services:
    crawler-app:
      image: docker.io/jarrar/crawler-app
      #build: ../crawler-app/
      hostname: crawler-app
      networks:
        crawler-net:
          aliases:
            - crawler-app
            - crawler-app.docker
      environment:
        - WEB_URL=http://crawler-web.docker:5080/api/v1.0/http_request
        - DB_URL=http://crawler-db.docker:5050/api/v1.0/http_record
        - PYTHONPATH=/app
        - PYTHONDONTWRITEBYTECODE=1
      #volumes:
        #- /tmp/docker/logs/app:/var/log

      ports:
        - "5000:5000"

    crawler-db:
      image: docker.io/jarrar/crawler-db
      #build: ../crawler-db/
      hostname: crawler-db
      networks:
        crawler-net:
          aliases:
            - crawler-db
            - crawler-db.docker
      environment:
        - WORKSPACE
      #volumes:
        #- /tmp/docker/logs/db:/var/log
      ports:
        - "5050:5050"
      environment:
        - PYTHONPATH=/app

    crawler-web:
      image: docker.io/jarrar/crawler-web
      #build: ../crawler-web/
      hostname: crawler-web
      networks:
        crawler-net:
          aliases:
            - crawler-web
            - crawler-web.docker
      environment:
        - WORKSPACE
      #volumes:
        #- /tmp/docker/logs/web:/var/log
      ports:
        - "5080:5080"
      environment:
        - PYTHONPATH=/app
