version: '2.1'

networks:
  crawler-net:
     driver: bridge

services:
    crawler-app:
      #image:
      build: ../crawler-app/
      hostname: crawler-app
      networks:
        crawler-net:
          aliases:
            - crawler-app
            - crawler-app.docker
      environment:
        - WORKSPACE
        - WEB_URL=http://crawler-web.docker:5080/api/v1.0/http_request
        - DB_URL=http://crawler-db.docker:5050/api/v1.0/http_record
        - PYTHONPATH=/webapp
      volumes:
        - $WORKSPACE/crawlers/crawler-app:/app
      ports:
        - "5000:5000"

