version: '2.1'

networks:
  crawler-net:
     driver: bridge

services:
    crawler-app:
      #image:
      build: ../crawler-app/
      hostname: crawler-app
      networks:
        crawler-net:
          aliases:
            - crawler-app
            - crawler-app.docker
      #volumes:
        #- D/var/lib/elk/data/elasticsearch:/var/lib/elasticsearch
      ports:
        - "5000:5000"

    crawler-db:
      #image:
      build: ../crawler-db/
      hostname: crawler-db
      networks:
        crawler-net:
          aliases:
            - crawler-db
            - crawler-db.docker
      #volumes:
        #- D/var/lib/elk/data/elasticsearch:/var/lib/elasticsearch
      ports:
        - "5050:5050"
